### ISSUE TITLE
error: object of type 'closure' is not subsettable

### ISSUE THREAD

**Issue by RGreensmith** [RGreensmith/MScResPACK#16]
https://github.com/RGreensmith/MScResPACK/blob/24c3bb6630298379e94f2088308770cebc5731c4/MScRes%20Scripts/glmm%20habitat%20modelling.R#L622

**Comment by RGreensmith** [comment]
so wont create bathymetryR for the next commands

**Comment by TomBennett-Lloyd** [comment]
https://github.com/RGreensmith/MScResPACK/blob/cb847591574b62369f53835f7853443417801c64/MScRes%20Scripts/glmm%20habitat%20modelling.R#L672

update to link in code

**Comment by RGreensmith** [comment]
Function doesn't return anything (other than printing off plots) so no objects from this function exist in local environment to subset from or use in any other way, objects exist within function environment, so need to return something to use it in local environment
